SELECT COUNTRY_ID, COUNTRY_NAME, C.REGION_ID, R.REGION_ID, REGION_NAME
FROM COUNTRIES C,
     REGIONS R
WHERE C.REGION_ID = R.REGION_ID;

-- 24
SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID = (SELECT MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 140);

-- 25
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE LOCATION_ID IN (SELECT LOCATION_ID
                      FROM LOCATIONS
                      WHERE COUNTRY_ID =
                            (SELECT COUNTRY_ID FROM COUNTRIES WHERE COUNTRY_NAME = 'United States of America'));

-- 26
SELECT E1.MANAGER_ID,
       E1.FIRST_NAME || ' ' || E1.LAST_NAME ANGAJAT,
       E2.EMPLOYEE_ID,
       E2.MANAGER_ID,
       E2.FIRST_NAME || ' ' || E2.LAST_NAME SEFUL_ANGAJATULUI,
       E3.EMPLOYEE_ID,
       E3.FIRST_NAME || ' ' || E3.LAST_NAME SEFUL_SEFULUI
FROM EMPLOYEES E1
       JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
       JOIN EMPLOYEES E3 ON E2.MANAGER_ID = E3.EMPLOYEE_ID;

-- 27
SELECT E1.EMPLOYEE_ID,
       E1.FIRST_NAME || ' ' || E1.LAST_NAME,
       E1.SALARY
FROM EMPLOYEES E1
WHERE E1.SALARY > (SELECT avg(E2.SALARY) FROM EMPLOYEES E2);

-- 28
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.HIRE_DATE,
       J.JOB_TITLE
FROM EMPLOYEES E
       JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE to_char(E.HIRE_DATE, 'MON') = 'MAR';

-- 29
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME     NAME,
       E.SALARY + E.SALARY * E.COMMISSION_PCT SALARIU_COMPLET,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E
       JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE (E.SALARY + E.SALARY * E.COMMISSION_PCT) > 12000;

-- 30
SELECT E.EMPLOYEE_ID,
       J.JOB_TITLE   OLD_JOB,
       JH.START_DATE OLD_JOB_START,
       JH.END_DATE   OLD_JOB_END
FROM EMPLOYEES E
       JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
       JOIN JOBS J ON JH.JOB_ID = J.JOB_ID;

-- 31
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.EMPLOYEE_ID,
       E.JOB_ID,
       J.JOB_TITLE                        OLD_JOB,
       JH.START_DATE                      OLD_JOB_START,
       JH.END_DATE                        OLD_JOB_END
FROM EMPLOYEES E
       JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
       JOIN JOBS J ON JH.JOB_ID = J.JOB_ID;

-- 32
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.EMPLOYEE_ID,
       E.JOB_ID,
       J2.JOB_TITLE                       CURR_JOB,
       J.JOB_TITLE                        OLD_JOB,
       JH.START_DATE                      OLD_JOB_START,
       JH.END_DATE                        OLD_JOB_END
FROM EMPLOYEES E
       JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
       JOIN JOBS J ON JH.JOB_ID = J.JOB_ID
       JOIN JOBS J2 ON E.JOB_ID = J2.JOB_ID;

-- 33
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.EMPLOYEE_ID,
       E.JOB_ID,
       J2.JOB_TITLE                       CURR_JOB,
       J.JOB_TITLE                        OLD_JOB,
       JH.START_DATE                      OLD_JOB_START,
       JH.END_DATE                        OLD_JOB_END
FROM EMPLOYEES E
       JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
       JOIN JOBS J ON JH.JOB_ID = J.JOB_ID
       JOIN JOBS J2 ON E.JOB_ID = J2.JOB_ID
WHERE E.JOB_ID IN JH.JOB_ID;

-- 34
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.EMPLOYEE_ID,
       E.JOB_ID,
       J2.JOB_TITLE                       CURR_JOB,
       D1.DEPARTMENT_NAME                 CURR_DPT,
       J.JOB_TITLE                        OLD_JOB,
       D2.DEPARTMENT_NAME                 OLD_DPT,
       JH.START_DATE                      OLD_JOB_START,
       JH.END_DATE                        OLD_JOB_END
FROM EMPLOYEES E
       JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
       JOIN JOBS J ON JH.JOB_ID = J.JOB_ID
       JOIN JOBS J2 ON E.JOB_ID = J2.JOB_ID
       JOIN DEPARTMENTS D1 ON E.DEPARTMENT_ID = D1.DEPARTMENT_ID
       JOIN DEPARTMENTS D2 ON JH.DEPARTMENT_ID = D2.DEPARTMENT_ID
WHERE E.JOB_ID IN JH.JOB_ID;

-- 35
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NAME,
       E.EMPLOYEE_ID,
       E.JOB_ID,
       J2.JOB_TITLE                       CURR_JOB,
       D1.DEPARTMENT_NAME                 CURR_DPT,
       J.JOB_TITLE                        OLD_JOB,
       D2.DEPARTMENT_NAME                 OLD_DPT,
       JH.START_DATE                      OLD_JOB_START,
       JH.END_DATE                        OLD_JOB_END
FROM EMPLOYEES E
       JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
       JOIN JOBS J ON JH.JOB_ID = J.JOB_ID
       JOIN JOBS J2 ON E.JOB_ID = J2.JOB_ID
       JOIN DEPARTMENTS D1 ON E.DEPARTMENT_ID = D1.DEPARTMENT_ID
       JOIN DEPARTMENTS D2 ON JH.DEPARTMENT_ID = D2.DEPARTMENT_ID
WHERE E.JOB_ID IN JH.JOB_ID
  AND D1.DEPARTMENT_ID != D2.DEPARTMENT_ID;


