SELECT DISTINCT E.LAST_NAME, E.EMPLOYEE_ID
FROM EMPLOYEES E
       JOIN WORK W ON E.EMPLOYEE_ID = W.EMPLOYEE_ID
WHERE E.EMPLOYEE_ID != 202
  AND (
        (SELECT PROJECT_ID FROM WORK W3 WHERE W3.EMPLOYEE_ID = 202)
        MINUS
        (SELECT PROJECT_ID FROM WORK W2 WHERE E.EMPLOYEE_ID = W2.EMPLOYEE_ID)) IS NULL;
