-- 32
SELECT to_char(sysdate, 'DY')         NUME_ZI
     , to_char(sysdate, 'D')          NR_ZI_SAPT
     , to_char(sysdate, 'DD')         NR_ZI_LUNA
     , to_char(sysdate, 'DDD')        NR_ZI_AN
     , to_char(sysdate, 'MM')         NR_LUNA
     , to_char(sysdate, 'MON')        NUME_LUNA_ABRV
     , to_char(sysdate, 'MONTH')      NUME_LUNA
     , to_char(sysdate, 'HH24:MM:SS') TIMP
FROM DUAL;

-- 33
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE LOCATION_ID = 1700
  AND MANAGER_ID IS NOT NULL;

-- 34
SELECT DISTINCT DEPARTMENTS.DEPARTMENT_ID
FROM DEPARTMENTS
       JOIN EMPLOYEES E ON DEPARTMENTS.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- 35
SELECT LAST_NAME, FIRST_NAME
FROM EMPLOYEES
WHERE to_char(HIRE_DATE, 'MON-YYYY') = 'JUN-1987';

-- 36
SELECT DISTINCT E.EMPLOYEE_ID
FROM EMPLOYEES E
       JOIN JOB_HISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
ORDER BY E.EMPLOYEE_ID;

-- 37
SELECT LAST_NAME || ' ' || FIRST_NAME NUME, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
  AND to_char(HIRE_DATE, 'MON-YYYY') = 'MAR-1997';

-- 38
SELECT JOB_TITLE
FROM JOBS
WHERE MAX_SALARY > 8000;

-- 39
SELECT *
FROM JOB_GRADES
WHERE 10000 BETWEEN LOWEST_SAL AND HIGHEST_SAL;

-- 40
SELECT unique LAST_NAME || ' ' || FIRST_NAME NUME
FROM EMPLOYEES
WHERE regexp_count(LAST_NAME || FIRST_NAME, 'l', 1, 'i') = 2;

-- 41
SELECT *
FROM EMPLOYEES
WHERE MANAGER_ID = 123;

-- 42
SELECT LAST_NAME || ' ' || FIRST_NAME NUME, SALARY, COMMISSION_PCT, SALARY + SALARY * COMMISSION_PCT VENIT
FROM EMPLOYEES
WHERE COMMISSION_PCT <= 0.25;
