-- 1
WITH DEPT_COSTURI AS (SELECT DEPARTMENT_NAME,
                             SUM(E.SALARY) DEPT_COST
                      FROM EMPLOYEES E,
                           DEPARTMENTS D
                      WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
                      GROUP BY DEPARTMENT_NAME)
SELECT DEPT_COST, (SELECT avg(DEPT_COST) FROM DEPT_COSTURI)
FROM DEPT_COSTURI
WHERE DEPT_COST > (SELECT avg(DEPT_COST) FROM DEPT_COSTURI)
ORDER BY DEPARTMENT_NAME;

WITH DEPT_COSTURI AS (SELECT DEPARTMENT_NAME,
                             SUM(SALARY) DEPT_COST
                      FROM EMPLOYEES E,
                           DEPARTMENTS D
                      WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
                      GROUP BY DEPARTMENT_NAME),
     MEDIE_COST AS (SELECT AVG(DEPT_COST) MEDIE FROM DEPT_COSTURI)
SELECT *
FROM DEPT_COSTURI,
     MEDIE_COST
WHERE DEPT_COST > MEDIE
ORDER BY DEPARTMENT_NAME;

-- 2
SELECT *
FROM (SELECT DEPARTMENT_NAME, SUM(SALARY) DEPT_COST
      FROM EMPLOYEES E,
           DEPARTMENTS D
      WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
      GROUP BY DEPARTMENT_NAME) DEPT_COSTURI
WHERE DEPT_COST > (SELECT avg(DEPT_COST)
                   FROM (SELECT DEPARTMENT_NAME, SUM(SALARY) DEPT_COST
                         FROM EMPLOYEES E,
                              DEPARTMENTS D
                         WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
                         GROUP BY DEPARTMENT_NAME) DEPT_COSTURI)
ORDER BY DEPARTMENT_NAME;

-- 3
SELECT DEPARTMENT_NAME,
       SUM(SALARY) DEPT_COST,
       max(MEDIA)
FROM EMPLOYEES E,
     DEPARTMENTS D,
     (
         SELECT round(AVG(SUM(SALARY))) MEDIA
         FROM EMPLOYEES E,
              DEPARTMENTS D
         WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
         GROUP BY DEPARTMENT_NAME) TABEL_MEDIA
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING SUM(SALARY) > max(MEDIA);

--
SELECT DEPARTMENT_NAME,
       sum(SALARY),
       (SELECT avg(sum(SALARY))
        FROM EMPLOYEES
        GROUP BY DEPARTMENT_ID),
       round(avg(SALARY), 2)
FROM DEPARTMENTS D,
     EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING sum(SALARY) > (SELECT avg(sum(SALARY))
                      FROM EMPLOYEES E,
                           DEPARTMENTS D
                      WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
                      GROUP BY E.DEPARTMENT_ID);

-- 5
SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES E
WHERE 5 > (SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY > E.SALARY)
ORDER BY SALARY DESC;
-- rank warehouse window top limit
SELECT *
FROM (SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM IN '';
-- linii de la 6 la 10

-- 8
SELECT LAST_NAME, SALARY, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE (DEPARTMENT_ID, SALARY) IN (
    SELECT DEPARTMENT_ID, MIN(SALARY)
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID);

SELECT LAST_NAME, SALARY, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES E
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID);

-- 11
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEES.DEPARTMENT_ID IS NOT NULL);

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID LIKE '%CLERK');

-- 12
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN
      (SELECT MANAGER_ID
       FROM EMPLOYEES
       WHERE MANAGER_ID IS NOT NULL);

-- 13
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE regexp_like(JOB_ID, 'clerk', 'i'));

-- 14
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ALL (
    SELECT avg(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID);

-- 15
SELECT LAST_NAME
FROM EMPLOYEES E
WHERE HIRE_DATE = (
    SELECT min(HIRE_DATE)
    FROM EMPLOYEES
    WHERE E.DEPARTMENT_ID = DEPARTMENT_ID
    GROUP BY DEPARTMENT_ID
);


-- pivot table

-- 18
-- a
SELECT 'nr total: ' || count(*) NUMAR
FROM EMPLOYEES
UNION ALL
SELECT 'nr 1997: ' || count(*)
FROM EMPLOYEES
--     where to_char(HIRE_DATE,'yyyy')=1997;
WHERE extract(YEAR FROM HIRE_DATE) = 1997;

-- b
SELECT count(*)  "nr total",
       max(A.NR) "nr 1997"
FROM EMPLOYEES,
     (SELECT count(EMPLOYEE_ID) NR
      FROM EMPLOYEES
      WHERE extract(YEAR FROM HIRE_DATE) = 1997) A;

SELECT (SELECT count(*) FROM EMPLOYEES)            "nr total",
       (SELECT count(EMPLOYEE_ID) NR
        FROM EMPLOYEES
        WHERE extract(YEAR FROM HIRE_DATE) = 1997) "nr 1997"
FROM DUAL;

-- 20 TODO
SELECT LAST_NAME, JOB_TITLE, DEPARTMENT_NAME, HIRE_DATE
FROM EMPLOYEES
         JOIN DEPARTMENTS D ON EMPLOYEES.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN JOBS J ON EMPLOYEES.JOB_ID = J.JOB_ID
UNION
SELECT LAST_NAME, JOB_TITLE, DEPARTMENT_NAME, START_DATE
FROM EMPLOYEES
         JOIN DEPARTMENTS D2 ON EMPLOYEES.DEPARTMENT_ID = D2.DEPARTMENT_ID
         JOIN JOB_HISTORY JH ON D2.DEPARTMENT_ID = JH.DEPARTMENT_ID
         JOIN JOBS J2 ON EMPLOYEES.JOB_ID = J2.JOB_ID;
-- 22
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM JOB_HISTORY;


SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE (EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID) IN (
    SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
    FROM JOB_HISTORY);


-- 23

SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID, LAST_NAME
FROM EMPLOYEES
INTERSECT
SELECT JH.EMPLOYEE_ID, JH.JOB_ID, JH.DEPARTMENT_ID, LAST_NAME
FROM JOB_HISTORY JH
         JOIN EMPLOYEES E ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID;

-- 25 a
SELECT EMPLOYEE_ID
FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID
FROM JOB_HISTORY;

-- 25 b
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM JOB_HISTORY);

-- 26
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
MINUS
(SELECT E.EMPLOYEE_ID, E.JOB_ID, E.DEPARTMENT_ID
 FROM JOB_HISTORY
          JOIN EMPLOYEES E ON JOB_HISTORY.EMPLOYEE_ID = E.EMPLOYEE_ID)

-- 27 a
SELECT LOCATION_ID
FROM LOCATIONS
MINUS
SELECT L.LOCATION_ID
FROM LOCATIONS L
         JOIN DEPARTMENTS
              ON L.LOCATION_ID = DEPARTMENTS.LOCATION_ID;

-- 27 b
SELECT LOCATION_ID
FROM LOCATIONS
WHERE LOCATION_ID NOT IN (
    SELECT L.LOCATION_ID
    FROM LOCATIONS L
             JOIN DEPARTMENTS
                  ON L.LOCATION_ID = DEPARTMENTS.LOCATION_ID);

-- 27 c
SELECT CITY
FROM LOCATIONS
MINUS
SELECT CITY
FROM LOCATIONS L
         JOIN DEPARTMENTS
              ON L.LOCATION_ID = DEPARTMENTS.LOCATION_ID;

SELECT CITY
FROM LOCATIONS
WHERE LOCATION_ID NOT IN (
    SELECT L.LOCATION_ID
    FROM LOCATIONS L
             JOIN DEPARTMENTS
                  ON L.LOCATION_ID = DEPARTMENTS.LOCATION_ID);
