CREATE TABLE CITITOR_IUGA AS
SELECT *
FROM CITITOR;
CREATE TABLE DOMENIU_IUGA AS
SELECT *
FROM DOMENIU;
CREATE TABLE CARTE_IUGA AS
SELECT *
FROM CARTE;
CREATE TABLE IMPRUMUTA_IUGA AS
SELECT *
FROM IMPRUMUTA;

-- 1
SELECT DISTINCT TITLU
FROM CARTE,
     IMPRUMUTA
WHERE CARTE.ID_CARTE = IMPRUMUTA.COD_CARTE
  AND DATAIM IN (SELECT min(DATAIM) FROM IMPRUMUTA);

-- 2
SELECT ID_CARTE, count(COD_CARTE)
FROM IMPRUMUTA,
     CARTE
WHERE COD_CARTE(+) = ID_CARTE
GROUP BY ID_CARTE
ORDER BY 2 DESC;

-- 3
SELECT DENUMIRE, count(TITLU), avg(PRET), sum(NREX)
FROM DOMENIU,
     CARTE
WHERE COD_DOMENIU(+) = ID_DOMENIU
GROUP BY DENUMIRE;

-- 4
SELECT count(count(COD_CARTE))
FROM IMPRUMUTA
GROUP BY COD_CARTE;

-- 5
SELECT ID_CARTE
FROM CARTE
WHERE ID_CARTE NOT IN (SELECT DISTINCT COD_CARTE FROM IMPRUMUTA);

-- 6

-- 7
SELECT ID_CARTE, min(TITLU), count(COD_CARTE)
FROM IMPRUMUTA,
     CARTE
WHERE COD_CARTE(+) = ID_CARTE
GROUP BY ID_CARTE
HAVING count(COD_CARTE) > 1;

-- 8
SELECT count(count(COD_CARTE))
FROM IMPRUMUTA
GROUP BY COD_CARTE
HAVING count(COD_CARTE) > 1;

-- 9
SELECT ID_DOMENIU, count(COD_CARTE)
FROM DOMENIU,
     CARTE,
     IMPRUMUTA
WHERE ID_DOMENIU = COD_DOMENIU(+)
  AND ID_CARTE = COD_CARTE(+)
  AND DATAEF IS NULL
GROUP BY ID_DOMENIU;

-- 10
SELECT COD_CITITOR, count(COD_CARTE)
FROM IMPRUMUTA
WHERE DATAEF IS NULL
  AND sysdate > DATARES
GROUP BY COD_CITITOR
HAVING count(COD_CARTE) > 1;

-- 11
SELECT ID_DOMENIU
FROM DOMENIU,
     CARTE
WHERE ID_DOMENIU = COD_DOMENIU(+)
  AND ID_CARTE IS NULL;

-- 12

-- 13

-- 14

-- 16
SELECT DISTINCT NUME
FROM CITITOR,
     IMPRUMUTA,
     CARTE
WHERE COD_CITITOR(+) = ID_CITITOR
  AND COD_CARTE = ID_CARTE(+)
  AND AUTOR NOT LIKE 'Autor5';

-- 17
SELECT max(NUME), count(DISTINCT ID_CARTE)
FROM CITITOR,
     CARTE,
     IMPRUMUTA,
     DOMENIU
WHERE ID_CARTE = COD_CARTE
  AND ID_CITITOR = COD_CITITOR
  AND ID_DOMENIU = COD_DOMENIU
GROUP BY ID_CITITOR, NUME
HAVING count(DISTINCT ID_CARTE) > 1;

-- 18
-- 19
-- 20
SELECT COD_CITITOR, COD_CARTE, DATAIM
FROM IMPRUMUTA J
WHERE DATAIM = (SELECT max(DATAIM) FROM IMPRUMUTA I WHERE I.COD_CITITOR = J.COD_CITITOR)
ORDER BY DATAIM DESC;

-- negatiua lui 19
-- titlurile cartilor si numarul de exemplare disponibile in prezent
SELECT TITLU,
       NREX - (SELECT count(*) FROM IMPRUMUTA WHERE COD_CARTE = ID_CARTE AND DATAEF IS NULL) DISPONIBIL
FROM CARTE
WHERE NREX - (SELECT count(*) FROM IMPRUMUTA WHERE COD_CARTE = ID_CARTE AND DATAEF IS NULL) > 0;

-- 22
SELECT *
FROM (SELECT ID_CARTE, PRET
      FROM CARTE
      ORDER BY PRET DESC)
WHERE ROWNUM <= 4;

SELECT ID_CARTE, TITLU, PRET
FROM CARTE C
WHERE (SELECT count(DISTINCT PRET) FROM CARTE WHERE PRET > C.PRET) < 4
ORDER BY PRET DESC;

-- 23
SELECT ID_CARTE,
       CASE
           WHEN PRET > 60 THEN 'scumpa'
           WHEN PRET >= 35 THEN 'medie'
           ELSE 'ieftina'
           END AS TIP
FROM CARTE;

-- 24
SELECT sum(decode(DENUMIRE, 'Informatica', 1, 0))                  NR_INFO,
       sum(decode(DENUMIRE, 'Literatura', 1, 0))                   NR_LIT,
       sum(decode(DENUMIRE, 'Informatica', 1, 'Literatura', 1, 0)) NR_INFOLIT,
       count(*)                                                    TOTAL
FROM DOMENIU,
     CARTE
WHERE ID_DOMENIU(+) = COD_DOMENIU;
-- b
SELECT sum(decode(DENUMIRE, 'Informatica', 1, 0))                                                 NR_INFO,
       round(sum(decode(DENUMIRE, 'Informatica', 1, 0)) / count(*) * 100) || '%'                  NR_INFO_PROC,
       sum(decode(DENUMIRE, 'Literatura', 1, 0))                                                  NR_LIT,
       round(sum(decode(DENUMIRE, 'Literatura', 1, 0)) / count(*) * 100) || '%'                   NR_LIT_PROC,
       sum(decode(DENUMIRE, 'Informatica', 1, 'Literatura', 1, 0))                                NR_INFOLIT,
       round(sum(decode(DENUMIRE, 'Informatica', 1, 'Literatura', 1, 0)) / count(*) * 100) || '%' NR_INFOLIT_PROC,
       count(*)                                                                                   TOTAL
FROM DOMENIU,
     CARTE
WHERE ID_DOMENIU(+) = COD_DOMENIU;

-- 25
SELECT COD_DOMENIU, COD_CITITOR, sum(PRET), grouping_id(COD_DOMENIU), grouping_id(COD_CITITOR)
FROM IMPRUMUTA,
     CARTE
WHERE ID_CARTE = COD_CARTE
  AND DATAEF IS NULL
GROUP BY ROLLUP (COD_DOMENIU, COD_CITITOR);

-- 26
SELECT COD_DOMENIU, COD_CITITOR, sum(PRET), grouping_id(COD_DOMENIU), grouping_id(COD_CITITOR)
FROM IMPRUMUTA,
     CARTE
WHERE ID_CARTE = COD_CARTE
  AND DATAEF IS NULL
GROUP BY CUBE (COD_DOMENIU, COD_CITITOR)
ORDER BY 1, 3;

-- 27
SELECT COD_DOMENIU, COD_CITITOR, sum(PRET)
FROM IMPRUMUTA,
     CARTE
WHERE ID_CARTE = COD_CARTE
  AND DATAEF IS NULL
GROUP BY GROUPING SETS ( (COD_DOMENIU, COD_CITITOR), ( ));

-- 28
SELECT NUME, count(DISTINCT ID_CARTE)
FROM CITITOR,
     IMPRUMUTA,
     CARTE
WHERE COD_CITITOR = ID_CITITOR
  AND COD_CARTE = ID_CARTE
  AND AUTOR = 'Autor5'
GROUP BY NUME
HAVING count(DISTINCT ID_CARTE) = (SELECT count(*) FROM CARTE WHERE AUTOR = 'Autor5');

-- 29
-- 30
UPDATE CARTE_IUGA
SET COD_DOMENIU = NULL
WHERE COD_DOMENIU NOT IN (SELECT DISTINCT ID_DOMENIU FROM DOMENIU);

-- 31

-- 42
-- a
SELECT COD_CITITOR, sum((DATAEF - DATARES) * 2)
FROM IMPRUMUTA_IUGA
WHERE
--       dataef is not null and
DATAEF > DATARES
GROUP BY COD_CITITOR;
-- b
SELECT COD_CITITOR, round(sum((sysdate - DATARES) * 2), 2)
FROM IMPRUMUTA_IUGA
WHERE DATAEF IS NULL
  AND sysdate > DATARES
GROUP BY COD_CITITOR;
-- c
SELECT COD_CITITOR, COD_CARTE, count(*)
FROM IMPRUMUTA_IUGA
WHERE (DATAEF IS NULL
    AND sysdate > DATARES)
   OR DATAEF > DATARES
GROUP BY COD_CITITOR, COD_CARTE
UNION ALL
SELECT COD_CITITOR, COD_CARTE, count(*)
FROM IMPRUMUTA_IUGA I
WHERE NOT exists(
        SELECT 1
        FROM IMPRUMUTA_IUGA
        WHERE I.COD_CITITOR = I.COD_CITITOR
            AND I.COD_CARTE = I.COD_CARTE
            AND DATARES <= DATAEF
           OR (DATAEF IS NULL AND DATARES > DATAEF)
    )
GROUP BY COD_CITITOR, COD_CARTE;

-- 44
SELECT UNIQUE ID_CITITOR, NUME
FROM CITITOR_IUGA C
WHERE NOT exists(SELECT COD_CARTE
                 FROM IMPRUMUTA_IUGA J
                 WHERE C.ID_CITITOR = J.COD_CITITOR
                 MINUS
                 SELECT COD_CARTE
                 FROM IMPRUMUTA_IUGA,
                      CITITOR_IUGA
                 WHERE COD_CITITOR = ID_CITITOR
                   AND CITITOR_IUGA.NUME = 'Cititor4')
  AND NUME != 'Cititor4';

-- 46
ALTER TABLE CITITOR_IUGA
    ADD (
        CONSTRAINT PK_CITITOR_IUGA PRIMARY KEY (ID_CITITOR),
        CONSTRAINT NN_NUME_CITITOR_IUGA CHECK ( NUME IS NOT NULL )
        );

-- 48
ALTER TABLE CARTE_IUGA
    ADD (
        CONSTRAINT PK_CARTE_IUGA PRIMARY KEY (ID_CARTE)
        );
-- 49
ALTER TABLE IMPRUMUTA_IUGA
    ADD (
        CONSTRAINT PK_IMPRUMUTA_IUGA PRIMARY KEY (COD_CARTE, COD_CITITOR, DATAIM),
        CONSTRAINT FK_IMPRUMUTA_CITITOR_IUGA FOREIGN KEY (COD_CITITOR) REFERENCES CITITOR_IUGA (ID_CITITOR) ,
        CONSTRAINT FK_IMPRUMUTA_CARTE_IUGA FOREIGN KEY (COD_CARTE) REFERENCES CARTE_IUGA (ID_CARTE) ,
        CONSTRAINT CK_IMPRUMUTA_IUGA CHECK (DATAEF >= DATAIM)
        );


ALTER TABLE IMPRUMUTA_IUGA
    MODIFY DATAIM DEFAULT sysdate;
